name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

env:
  NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
jobs:
  # for Pull Request (exclude merged)
  pullreq_build:
    name: Build(pullreq)
    if: (github.repository == 'yyamazaki1732/kuroco-site' && github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
      - name: "Get branch name and sha"
        id: get_branch
        run: |
          PR=$(curl -H "Authorization: token 80cfbf816f2f76e1ad2c524bbd916484" https://kamenosuke.g.kuroco.app/direct/menu/github/?pr=${{ github.event.issue.pull_request.url }})
          echo "branch=$(echo $PR | jq -r '.ref')" >> $GITHUB_OUTPUT
          echo "sha=$(echo $PR | jq -r '.sha')" >> $GITHUB_OUTPUT
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_branch.outputs.branch }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Generate
      #   run: npm run generate
      # - name: Zip artifact for upload
      #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_branch.outputs.sha }}-${{ github.run_id }}
          path: out
          retention-days: 7
      - name: Wait for Artifact download
        run: sleep 15
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://kamenosuke.g.kuroco.app/direct/menu/github/"
          webhook_secret: "80cfbf816f2f76e1ad2c524bbd916484"
          data: '{"single_zip":"0","domain":"kamenosuke.g.kuroco-front.app","pr":"${{ github.event.issue.pull_request.url }}",  "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ steps.get_branch.outputs.sha }}"}'

  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'yyamazaki1732/kuroco-site' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Generate
      #   run: npm run generate
      # - name: Zip artifact for upload
      #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: out
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://kamenosuke.g.kuroco.app/direct/menu/github/"
          webhook_secret: "80cfbf816f2f76e1ad2c524bbd916484"
          data: '{"single_zip":"0","domain":"kamenosuke.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
